"""add_quality_check_fields_to_project_sections

Revision ID: 08fcf247e131
Revises: 572727e8a07a
Create Date: 2026-03-02 15:12:06.582193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fcf247e131'
down_revision: Union[str, Sequence[str], None] = '572727e8a07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_sections', sa.Column('quality_issues', sa.JSON(), nullable=True))
    op.add_column('project_sections', sa.Column('quality_checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_sections', 'quality_checked_at')
    op.drop_column('project_sections', 'quality_issues')
    # ### end Alembic commands ###
