"""add_papers_and_profile_tables

Revision ID: 3dff3d9d5689
Revises: a1b2c3d4e5f6
Create Date: 2026-02-27 16:50:57.733024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dff3d9d5689'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_configs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=100), server_default=sa.text("'openai'"), nullable=False),
    sa.Column('model', sa.VARCHAR(length=200), server_default=sa.text("'gpt-4o-mini'"), nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=500), server_default=sa.text("('')"), nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=500), server_default=sa.text("('')"), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
