"""add_new_tables

Revision ID: 453a0d6acd63
Revises: 3dff3d9d5689
Create Date: 2026-02-27 17:02:35.085995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453a0d6acd63'
down_revision: Union[str, Sequence[str], None] = '3dff3d9d5689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('scientific_significance', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=500), nullable=True),
    sa.Column('grant_number', sa.String(length=100), nullable=True),
    sa.Column('grant_type', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.String(length=7), nullable=True),
    sa.Column('end_date', sa.String(length=7), nullable=True),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['applicant_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=7), nullable=True),
    sa.Column('end_date', sa.String(length=7), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['applicant_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_papers')
    op.drop_table('work_experiences')
    op.drop_table('project_histories')
    op.drop_table('papers')
    op.drop_table('applicant_profile')
    # ### end Alembic commands ###
