"""add_title_is_active_to_conversations

Revision ID: 572727e8a07a
Revises: 12475186395a
Create Date: 2026-03-02 13:05:55.347895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572727e8a07a'
down_revision: Union[str, Sequence[str], None] = '12475186395a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(length=200), nullable=False, server_default='对话 1'))
    op.add_column('conversations', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###

    # Data migration: for any (project_id, section_id) groups with multiple rows,
    # keep only the min-id row as active; set all others to is_active=False.
    conn = op.get_bind()
    conn.execute(sa.text("""
        UPDATE conversations
        SET is_active = CASE
            WHEN id = (
                SELECT MIN(id) FROM conversations c2
                WHERE c2.project_id = conversations.project_id
                AND (c2.section_id = conversations.section_id
                     OR (c2.section_id IS NULL AND conversations.section_id IS NULL))
            ) THEN 1
            ELSE 0
        END
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_active')
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
