"""add generation plan fields to project_sections

Revision ID: bd728b6c2079
Revises: 8abb01f1c692
Create Date: 2026-02-26 17:41:04.469336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd728b6c2079'
down_revision: Union[str, Sequence[str], None] = '8abb01f1c692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_sections', sa.Column('generation_plan', sa.JSON(), nullable=True))
    op.add_column('project_sections', sa.Column('generation_cursor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_sections', 'generation_cursor')
    op.drop_column('project_sections', 'generation_plan')
    # ### end Alembic commands ###
